import { Inter,Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight:['100','200','300','400','500','600','700','800','900'],
  subsets:['latin'],
  variable:'--font-poppins',
})

const inter = Inter({
  weight:['100','200','300','400','500','600','700','800','900'],
  subsets:['latin'],
  variable:'--font-inter',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
